### ISSUE TITLE
Joomla 3.5 does not output bootstrap classes front-end

### ISSUE THREAD

**Issue by wderuijter** [nn-medienagentur/plg_system_nnbootstrapparams#5]
When using J!3.5 the Joomla Bootstrap Params plugin for modules still works in the backend. On the frontend of the site however, the classes are not applied to the modules.

**Comment by nn-medienagentur** [comment]
@wderuijter please check the new version or [https://github.com/nn-medienagentur/plg_system_kicktempparams](url). in kicktempparams plugin I do not overwrite any classes, because the update problem. If you use the kicktempparams plugin, you have to create or edit in your template the modules.php.

For example:
[https://github.com/nn-medienagentur/kicktemp/blob/master/html/modules.php#L14](url) change params
[https://github.com/nn-medienagentur/kicktemp/blob/master/html/modules.php#L65](url) changaparams function 

and adding the new class [https://github.com/nn-medienagentur/kicktemp/blob/master/html/modules.php#L24](url)
